CREATE TABLE users (
  id UUID PRIMARY KEY,
  email TEXT NOT NULL UNIQUE CHECK (email = lower(email)),
  password_hash TEXT NOT NULL,
  name TEXT NOT NULL,
  lastname TEXT NOT NULL DEFAULT '',
  specialty TEXT NOT NULL DEFAULT 'Medicina Interna',
  target TEXT NOT NULL DEFAULT '2027',
  plan TEXT NOT NULL DEFAULT 'basic' CHECK (plan IN ('basic', 'premium')),
  preferences JSONB NOT NULL DEFAULT '{"reminders":true,"sound":false}',
  bonus_tokens INTEGER NOT NULL DEFAULT 0 CHECK (bonus_tokens BETWEEN 0 AND 30),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE auth_sessions (
  token_hash TEXT PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  csrf_token TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX auth_sessions_user ON auth_sessions(user_id);
CREATE INDEX auth_sessions_expiry ON auth_sessions(expires_at);
CREATE TABLE password_resets (
  token_hash TEXT PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX password_resets_user ON password_resets(user_id);
CREATE TABLE questions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area TEXT NOT NULL,
  topic TEXT NOT NULL,
  text TEXT NOT NULL,
  options JSONB NOT NULL CHECK (jsonb_typeof(options) = 'array' AND jsonb_array_length(options) = 4),
  answer SMALLINT NOT NULL CHECK (answer BETWEEN 0 AND 3),
  explanation TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  sample BOOLEAN NOT NULL DEFAULT false,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX questions_area_topic ON questions(area, topic) WHERE active;
CREATE TABLE quiz_sessions (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  mode TEXT NOT NULL CHECK (mode IN ('rapido','repaso','inteligente','personalizado','flashcards')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','completed','abandoned')),
  title TEXT NOT NULL,
  current_index INTEGER NOT NULL DEFAULT 0 CHECK (current_index >= 0),
  requested_count INTEGER NOT NULL CHECK (requested_count BETWEEN 1 AND 100),
  token_cost INTEGER NOT NULL DEFAULT 0 CHECK (token_cost >= 0),
  mission SMALLINT CHECK (mission BETWEEN 0 AND 6),
  config JSONB NOT NULL DEFAULT '{}',
  total INTEGER NOT NULL CHECK (total BETWEEN 1 AND 100),
  correct INTEGER,
  score INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX one_active_quiz_per_user ON quiz_sessions(user_id) WHERE status = 'active';
CREATE INDEX quiz_sessions_history ON quiz_sessions(user_id, finished_at DESC) WHERE status = 'completed';
CREATE TABLE session_questions (
  session_id UUID NOT NULL REFERENCES quiz_sessions(id) ON DELETE CASCADE,
  question_id INTEGER NOT NULL REFERENCES questions(id),
  position INTEGER NOT NULL CHECK (position >= 0),
  snapshot JSONB NOT NULL,
  answer SMALLINT CHECK (answer BETWEEN 0 AND 3),
  rating TEXT CHECK (rating IN ('Difícil','Regular','Fácil')),
  revealed_at TIMESTAMPTZ,
  PRIMARY KEY (session_id, question_id),
  UNIQUE (session_id, position)
);
CREATE TABLE bookmarks (
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  question_id INTEGER NOT NULL REFERENCES questions(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, question_id)
);
CREATE TABLE mission_progress (
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  day SMALLINT NOT NULL CHECK (day BETWEEN 0 AND 6),
  session_id UUID NOT NULL REFERENCES quiz_sessions(id),
  completed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, day)
);
CREATE TABLE daily_usage (
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  day DATE NOT NULL,
  spent INTEGER NOT NULL DEFAULT 0 CHECK (spent BETWEEN 0 AND 10),
  PRIMARY KEY (user_id, day)
);
CREATE TABLE study_days (
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  day DATE NOT NULL,
  PRIMARY KEY (user_id, day)
);
